### PR TITLE
Update to Stubparser version 3.26.1

### LINKED ISSUE #5575: WPI crashes when the sealed/non-sealed keywords are encountered
`sealed` and `non-sealed` are valid Java keywords in Java 17. However, WPI crashes when it encounters these keywords, as demonstrated by the following test, borrowed from the Java documentation (which is checked in on [this branch](https://github.com/kelloggm/checker-framework/tree/sealed-javaparser-crash)):

```
// @below-java17-jdk-skip-test
// from https://docs.oracle.com/en/java/javase/15/language/sealed-classes-and-interfaces.html

public sealed class Figure
// The permits clause has been omitted
// as its permitted classes have been
// defined in the same file.
{}

final class Circle extends Figure {
  float radius;
}

non-sealed class Square extends Figure {
  float side;
}

sealed class Rectangle extends Figure {
  float length, width;
}

final class FilledRectangle extends Rectangle {
  int red, green, blue;
}
```

The stack trace is the following:
```    java.lang.RuntimeException: com.github.javaparser.ParseProblemException: (line 4,col 1) Parse error. Found  "sealed" <IDENTIFIER>, expected one of  ";" "@" "class" "enum" "interface" "module" "open" "record"
    Problem stacktrace :
      com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:14094)
      com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13939)
      com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:405)
      com.github.javaparser.JavaParser.parse(JavaParser.java:127)
      com.github.javaparser.JavaParser.parse(JavaParser.java:242)
      org.checkerframework.framework.util.JavaParserUtil.parseCompilationUnit(JavaParserUtil.java:88)
      org.checkerframework.common.wholeprograminference.WholeProgramInferenceJavaParserStorage.addSourceFile(WholeProgramInferenceJavaParserStorage.java:511)
      org.checkerframework.common.wholeprograminference.WholeProgramInferenceJavaParserStorage.addClassTree(WholeProgramInferenceJavaParserStorage.java:490)
      org.checkerframework.common.wholeprograminference.WholeProgramInferenceJavaParserStorage.preprocessClassTree(WholeProgramInferenceJavaParserStorage.java:466)
      org.checkerframework.common.wholeprograminference.WholeProgramInferenceImplementation.preprocessClassTree(WholeProgramInferenceImplementation.java:987)
      org.checkerframework.framework.type.AnnotatedTypeFactory.setRoot(AnnotatedTypeFactory.java:859)
      org.checkerframework.framework.type.GenericAnnotatedTypeFactory.setRoot(GenericAnnotatedTypeFactory.java:429)
...
```

This is pretty clearly a problem with JavaParser, which doesn't support features introduced in Java 14 or later (`sealed` and `non-sealed` were introduced in Java 15). However, I don't think WPI should crash in these cases: it would be better to e.g. not generate a .ajava file.

@mernst I think this is yet another reason to move away from JavaParser for parsing .ajava files, if you're still pursuing that. We encountered this when trying to run WPI on https://github.com/eponymouse/columnal, which requires Java 17 to build and extensively uses Java 17 features - it was also impacted by the fix in #5542, whose application lead to the discovery of this problem.

### LINKED ISSUE #6648: Update to JavaParser 3.26.0
Release notes: https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-3.26.0

This fixes https://github.com/javaparser/javaparser/issues/4041, which was impacting WPI on certain programs that use `sealed` as a variable name.

I think updating JavaParser is a bit involved / risky so I wanted to open an issue first

FYI @iamsanjaymalakar

### PR DESCRIPTION
**Pull request by smillst**
Fixes #5575 and fixes #6648.

### CODE REVIEW

**Comment by msridhar** [comment]
@smillst could you add a test that uses `sealed` as the name of a local variable? That was the issue we were running into motivating #6648

**Comment by smillst** [comment]
> @smillst could you add a test that uses `sealed` as the name of a local variable? That was the issue we were running into motivating #6648

I added a test case: framework/tests/all-systems/java17/Figure.java.

**Comment by msridhar** [comment]
> > @smillst could you add a test that uses `sealed` as the name of a local variable? That was the issue we were running into motivating #6648
> 
> 
> 
> I added a test case: framework/tests/all-systems/java17/Figure.java.

Yes but I don't think it tries to use `sealed` as the name of a local variable, which is legal since `sealed` is a special type of keyword.

**Review by mernst — APPROVED** [review]
Thanks!

**Pull request merged**
