### PR TITLE
Reset uninferredTypeArgumentScanner.

### LINKED ISSUE #3851: 3.7.1: uninferredTypeArgumentScanner consumes significant amount of memory in AnnotatedTypeMirror
Apparently, verification of Calcite codebase requires to bump `-Xmx` to 2g or something like that, and it turns out noticeable memory is taken by `SimpleAnnotatedTypeScanner`:

https://github.com/typetools/checker-framework/blob/9dbf0c7c06210a9cb926242a8181eb0dd888ab04/framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java#L813-L820

Could it be a static instance and/or `ThreadLocal`?

`NullnessAnnotatedTypeFactory` consumed ~50MiB

Снимок экрана 2020-11-04 в 1 10 30

~ 50% of that was consumed by empty `IdentityHashMap` in `SimpleAnnotatedTypeScanner`

Снимок экрана 2020-11-04 в 1 11 01

There are 72226 `SimpleAnnotatedTypeScanner` instances which are referenced from `AnnotatedTypeMirror$...` classes

Снимок экрана 2020-11-04 в 1 11 29

### PR DESCRIPTION
**Pull request by smillst**
Fixes #3851.

### CODE REVIEW

**Comment by vlsi** [comment]
It won't help, since:
1) `IdentityHashMap` does not de-allocate backing array
2) It won't reduce the number of `SimpleAnnotatedTypeScanner` instances

**Comment by smillst** [comment]
@vlsi How about not saving the anonymous class in a field?

**Comment by vlsi** [comment]
That would reduce memory consumption, however, I wonder if that would impact verification time (e.g. re-instantiation might take time).

**Comment by smillst** [comment]
@vlsi I moved `uninferredTypeArgumentScanner` to the AnnotatedTypeFactory.  In that location, there should only be one scanner.  Thanks for your comments!

**Review by mernst — APPROVED** [review]

**Comment by mernst** [comment]
Let's see how this impacts memory and run time.  If its impact is negative, we can revert it.

**Pull request merged**
