### PR TITLE
Fix on Issue 2432: exclude type variable when replacing poly annotations

### PR DESCRIPTION
**Pull request by abslamp**
Test case and one possible fix on #2432 
Excluding type variables with concrete type arguments ("E" TypeVar) in lub calculation and poly annotation replacement.
Type variables with no assigned arguments ("T" TypeVar) are not affected. (e.g. when visiting void \<T\> fun(T) , T is not excluded)

### CODE REVIEW

**Comment by mernst** [comment]
Please use a descriptive title, not just "Issue 2432".  You should also add "fixes #NNNN" which is useful, but does not describe the work you have done.  Thanks!

**Comment by abslamp** [comment]
Logic proven wrong. A new fix: https://github.com/typetools/checker-framework/pull/2643

**Comment by wmdietl** [comment]
Did you push something to this branch in error? Wasn't this replaced by the changes in #2643?

**Comment by abslamp** [comment]
@wmdietl I plan to test some logic on this clean branch to trigger check. After that, I will close this PR again.

**Pull request closed without merging**
