### PR TITLE
Test under Java 21

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

**Comment by smillst** [comment]
I merged this branch with a branch that include `case null` in https://github.com/smillst/checker-framework/tree/java-21-testcase.  It has the following failure:
```
 1 unexpected diagnostic was found:
      Issue6173.java:10: error: null in switch cases is a preview feature and is disabled by default. 
```
https://dev.azure.com/smillst/checker-framework/_build/results?buildId=3074&view=logs&j=e43dad68-5e3b-5c73-4a4a-12eda19916b0&t=fbbfbd16-76f1-5ebc-8cbf-485046fc23ef&l=7163

So I don't think the docker image is setup properly.

**Comment by mernst** [comment]
The docker image looks right to be.  Outside Docker, running `javac -version Issue6173.java` yields:

```
javac 21-ea
Issue6173.java:10: error: null in switch cases is a preview feature and is disabled by default.
      case null -> throw new IllegalArgumentException("GroupBy parameter is required");
           ^
  (use --enable-preview to enable null in switch cases)
1 error
```

Maybe that feature is still a preview, or the Ubuntu `openjdk-21-jdk` package is a relatively old version of JDK 21.

**Comment by smillst** [comment]
> The docker image looks right to be. Outside Docker, running `javac -version Issue6173.java` yields:
> 
> ```
> javac 21-ea
> Issue6173.java:10: error: null in switch cases is a preview feature and is disabled by default.
>       case null -> throw new IllegalArgumentException("GroupBy parameter is required");
>            ^
>   (use --enable-preview to enable null in switch cases)
> 1 error
> ```
> 
> Maybe that feature is still a preview, or the Ubuntu `openjdk-21-jdk` package is a relatively old version of JDK 21.

It's not a preview feature in JDK 21: https://jdk.java.net/21/release-notes#441

When I run `javac -version Issue6173.java` locally, I just get:
```
javac 21
```

So I suspect the package is old. I downloaded JDK 21 from here: https://jdk.java.net/21/

**Comment by mernst** [comment]
In Ubuntu 23.04, openjdk-21-jdk is "21~14ea".
In Ubuntu 23.10 (which has not yet been released), openjdk-21-jdk is "21~35ea".
I will change the Docker images for JDK 21 to use the unreleased version of Ubuntu.

**Pull request closed without merging**
