### PR TITLE
Document necessary build configuration for including stub files in a checker

### PR DESCRIPTION
**Pull request by msridhar**
See #3720.  This change fixes the manual.  I will open a separate PR for the template checker before closing the issue.

### CODE REVIEW

**Review by mernst — APPROVED** [review]
Thanks for the documentation.

**Comment by msridhar** [comment]
Should I go ahead and merge this?  Not sure about the protocol around merging to master

**Comment by mernst** [comment]
You may squash-and-merge it.   I didn't do so because you said "I will open a separate PR for the template checker before closing the issue.", and I hadn't seen that yet at https://github.com/typetools/templatefora-checker/pulls .

**Comment by msridhar** [comment]
Thanks.  Issue #3720 will remain open after merging this so I won't forget about the other PR

**Pull request merged**
