### PR TITLE
Add index annotations to CharSequence

### PR DESCRIPTION
**Pull request by panacekcz**
Previously, `java.lang.CharSequence` did not have upper-bound and samelen annotations on the return type. That prevented geting `@IndexFor` or `@SameLen` for a mutable sequence (`StringBuilder`), but caused false positives in code using `CharSequence`.

This PR adds the annotations.

### CODE REVIEW

**Comment by panacekcz** [comment]
Travis failure is fixed by mernst/plume-lib#40. Unfortunately this adds 2 new `@SuppressWarnigns` to plume-lib.

**Comment by panacekcz** [comment]
This should be merged at the same time as or after mernst/plume-lib#40.
If it is merged before, then type-checking plume-lib with the Index Checker will fail before the other one is merged.

**Comment by smillst** [comment]
I merged mernst/plume-lib#40.  So I'll restart these tests then merge this pull request.

**Comment by mernst** [comment]
Weird merge conflict.  I'll look into this shortly (but not immediately).

**Comment by mernst** [comment]
I think Suzanne resolved this before I did, and I was confused why it wasn't getting Suzanne's commit.  Will wait for test to pass.

**Comment by smillst** [comment]
I just merged master into this branch to see if that would fix the problem.  Hopefully it will pas now.

**Pull request merged**
