### PR TITLE
Add @Documented to framework annotations

### PR DESCRIPTION
**Pull request by xingweitian**

### CODE REVIEW

**Comment by smillst** [comment]
`PostconditionAnnotation` and `PreconditionAnnotation` are also not annotated with `@Documented`.  Should they be?

**Comment by wmdietl** [comment]
Yes, I think it makes sense for all the framework annotations to be `@Documented`.
In `framework/src/main/java/org/checkerframework/framework/qual` I did `grep -L Documented` and get:

```
AnnotatedFor.java
CFComment.java
ConditionalPostconditionAnnotation.java
DefaultQualifierForUse.java
FieldInvariant.java
FromByteCode.java
FromStubFile.java
JavaExpression.java
LiteralKind.java
MonotonicQualifier.java
NoDefaultQualifierForUse.java
package-info.java
PostconditionAnnotation.java
PreconditionAnnotation.java
QualifierArgument.java
QualifierForLiterals.java
TypeKind.java
TypeUseLocation.java
```

Let's discuss each:
- `AnnotatedFor` probably useful to see this in javadoc
- `CFComment` would also seem good
- `ConditionalPostconditionAnnotation` yes
- `DefaultQualifierForUse` yes
- `FieldInvariant` yes
- `FromByteCode` not used in source code
- `FromStubFile` not used in source code
- `JavaExpression` seems useful, yes
- `LiteralKind` enum, not applicable
- `MonotonicQualifier` yes
- `NoDefaultQualifierForUse` yes
- `package-info.java` not applicable
- `PostconditionAnnotation` yes
- `PreconditionAnnotation` yes
- `QualifierArgument` yes
- `QualifierForLiterals` yes
- `TypeKind` enum, not applicable
- `TypeUseLocation` enum, not applicable

@smillst Any one of those you see differently?
@xingweitian please expand the PR and don't forget about the separate PR for Conditional annos on constructors.

**Comment by smillst** [comment]
@wmdietl I agree with your list.  Thanks!

**Comment by wmdietl** [comment]
@xingweitian Could you also see whether there are places in the manual that should be updated?
Updates to the examples in https://github.com/typetools/checker-framework/blob/master/docs/manual/creating-a-checker.tex and maybe a note about `@Documented` there would be good.
Thanks!

**Pull request merged**
