### PR TITLE
Additional units for unit checker; fixes #4116

### LINKED ISSUE #4116: Support additional (derived) units in units checker
The units checker is already quite helpful but could support more derived units.

### Currently Supported Units
|name and symbol|unit(s)           |
|---------------|------------------|
|acceleration¹ a|m/s²              |
|angle φ        |rad (m/m), deg (°)|
|area¹ A        |m², mm², km²      |
|current I      |A                 |
|length ℓ, s    |m, mm, km         |
|luminance Iᵥ   |cd                |
|mass m         |kg, g             |
|speed¹ v       |m/s               |
|substance n    |mol               |
|temperature T  |K, C (°C)         |
|time t         |s                 |

### Useful Additional Units
|name and symbol   |unit(s)                        |
|------------------|-------------------------------|
|area¹ A           |ha (10000m²), dm², cm²         |
|capacitance² C    |F (C/V)                        |
|charge¹ q         |C (A s)                        |
|energy² E, work² W |J (N m, W s), kWh              |
|force¹ F          |N (kg m/s²), kN (t m/s²)       |
|length¹ ℓ, s      |dm, cm                         |
|mass m            |t                              |
|(el.) potential² U|V (W/A)                        |
|power² P          |W (J/s)                        |
|pressure² p       |Pa (N/m²)                      |
|resistence² R     |Ω (V/A)                        |
|solid angle Ω     |sr (m²/m²)                     |
|volume¹ V         |m³, mm³, km³, ℓ (dm³), dm³, cm³|

**Key**
¹ 1st order
² 2nd order

### Motivation for some additional units
- Density: [ρ] = g/cm³ = kg/m³
- Work: kWh often used for electric power consumption
- Area: ha often used in land measurement

### Further discussion
- Unfortunately, the unit `C` is already used in the units checker for the derived SI unit _degrees Centigrade_, so something else needs to be thought of for electric charge Coulomb.
- “Unusal” units (e.g. ha, ℓ)? At least for conversion to SI?
  - `@m2 int fromHektarToSquareMeter(@ha int hektar) { return hektar * 10000; }`
  - `@m3 int fromLiterToCubicMeter(@l int liter) { return liter / 1000; } // better @dm3?`
  - Probably better to leave out ℓ, dm³ and cm³ as relations are rather trival?
- Imperial units? At least for conversion to SI?
- Which relations to include? E.g. only those given (by lines) in https://physics.nist.gov/cuu/Units/SIdiagram.html
  - A = ℓ³, F = m a, p = F/A
  - W = F s, P = W/s = U I
  - q = I t, C = q/U, U = P/A = R I
- Additional derived units to include?
  - radioactive: Gy, Sv, Bq, Hz
  - electromagnetic: Wb, H, T
  - (bio)chemistry: kat (use is encouraged but adoption slow)
  - photometric: lx, lm

I'd like to create a PR after discussing what to actually include. Should the discussion happen here or in the PR itself?
Note: I've already created https://github.com/rkraneis/checker-extensions so hopefully somewhat know my way around. I probably still need some pointers on how to update the documentation (found `untits-checker.tex`, is that enough?).

~Edit: draft PR to drive discussion https://github.com/rkraneis/checker-framework/pull/1~

### PR DESCRIPTION
**Pull request by rkraneis**

### CODE REVIEW

**Comment by rkraneis** [comment]
I only implemented `@Volume` for now in the obvious way (including updates to tests and documentation); other interesting units are mentioned in issue #4116. When it is clear that I didn't miss anything technical for `@Volume` and which additional units to support, I will add those.

**Review by mernst — COMMENTED** [review]
This looks great.  Thanks very much for the contribution.  I only fixed one typo.

Please go ahead and add other units, and let me know when I should re-review.

**Comment by mernst** [comment]
@rkraneis Please let us know if there is anything we can do to help.

I'm not trying to nag -- it's just that we are eager for this improvement.  Thanks!

**Comment by rkraneis** [comment]
@mernst I'm a bit tight on time at the moment, but will be able to tackle the topic again over Easter.

**Comment by mernst** [comment]
OK, thanks for letting me know.  Good luck with everything.

**Comment by rkraneis** [comment]
Hi @mernst, two things actually do give me a little bit of a hard time (both around testing):

1. IntelliJ always claims the test files (checker-framework/checker/tests/units/*.java) to be error free. Is this related to the non-trivial Gradle setup? (I'm neither an IntelliJ nor a Gradle user, but my IDE of choice completely choked on the build scripts). Actual compilation issues can only be (kind of?) seen when manually running `./gradlew :checker:UnitsTest`; which brings me to my second point
2. Even when running with the advertised additional debug parameter `./gradlew -Pemit.test.debug :checker:UnitsTest` I don't get that helpful output:

```
$ ./gradlew -Pemit.test.debug :checker:UnitsTest

> Task :checker:UnitsTest

org.checkerframework.checker.test.junit.UnitsTest > run[/home/rene/Projekte/typetools/checker-framework/checker/units] STANDARD_OUT
    Running test using the following invocation:
    javac -processor org.checkerframework.checker.units.UnitsChecker ...
    ---------------- start of javac ouput ----------------

    ---------------- end of javac ouput ----------------

org.checkerframework.checker.test.junit.UnitsTest > run[/home/rene/Projekte/typetools/checker-framework/checker/units] FAILED
    java.lang.AssertionError: 104 out of 138 expected diagnostics were found.
    6 unexpected diagnostics were found:
    SubtractionUnits.java:167: error: cannot find symbol
    SubtractionUnits.java:168: error: cannot find symbol
    SubtractionUnits.java:35: error: (type.checking.not.run)
    TypeVarsArrays.java:1: error: (type.checking.not.run)
    Units.java:7: error: (type.checking.not.run)
    UnqualTest.java:3: error: (type.checking.not.run)
    34 expected diagnostics were not found:
    SubtractionUnits.java:200: error: (assignment.type.incompatible)
    SubtractionUnits.java:204: error: (assignment.type.incompatible)
    SubtractionUnits.java:208: error: (assignment.type.incompatible)
    SubtractionUnits.java:212: error: (assignment.type.incompatible)
    SubtractionUnits.java:216: error: (assignment.type.incompatible)
    SubtractionUnits.java:220: error: (assignment.type.incompatible)
    SubtractionUnits.java:224: error: (assignment.type.incompatible)
    SubtractionUnits.java:228: error: (assignment.type.incompatible)
    SubtractionUnits.java:232: error: (assignment.type.incompatible)
...
```
(that is, there is no “javac output”, so figuring out what I missed is a bit tiresome)

**Comment by rkraneis** [comment]
Another problem around automatic reformatting:
```java
    // :: error: (assignment.type.incompatible)
    @N(Prefix.giga) int notN = N;
```
always gets reformatted to
```java
    // :: error: (assignment.type.incompatible)
    @N(Prefix.giga)
    int notN = N;
```
I can rewrite this to 
```java
    @N(Prefix.giga)
    // :: error: (assignment.type.incompatible)
    int notN = N;
```
to make the tests still pass, but it's definitely not optimal. This does not happen for `@m(...)`, though.

**Comment by rkraneis** [comment]
And one more observation: Unfortunately, the unit _C_ (instead of the unrepresentable _°C_) is already used in the units checker for the derived SI unit _degrees Centigrade_, so something else needs to be thought of for the electric charge Coulomb, if it should be added.

**Review by mernst — APPROVED** [review]
Thanks very much for these additional units!  I appreciate your contribution.

**Pull request merged**
