### PR TITLE
Add signedness annotations in java.util.Array, java.util.Random and java.security.SecureRandom

### PR DESCRIPTION
**Pull request by gokaco**
Work in progress.

### CODE REVIEW

**Comment by mernst** [comment]
This doesn't look ready to review yet (you can mark the pull request as "draft" when you create it if you want).  Please let me know when it is ready.  Thanks!

**Comment by gokaco** [comment]
> This doesn't look ready to review yet (you can mark the pull request as "draft" when you create it if you want). Please let me know when it is ready. Thanks!

Mike, as this pull request has been issued, I think it cannot be made as "draft". I can write in the description "Work in progress"
Or
I should close it again and start afresh "draft" pull request?

**Comment by mernst** [comment]
> > This doesn't look ready to review yet (you can mark the pull request as "draft" when you create it if you want). Please let me know when it is ready. Thanks!
> 
> Mike, as this pull request has been issued, I think it cannot be made as "draft". I can write in the description "Work in progress"
> Or
> I should close it again and start afresh "draft" pull request?

All that is needed is to tell me when it's ready (as you did).
My remark about "draft" pull requests was for the future, when you create a pull request.

**Comment by mernst** [comment]
This pull request looks good.  Thanks for the library annotations!

**Pull request merged**
