### PR TITLE
Generate OSGi manifest for checker-qual

### PR DESCRIPTION
**Pull request by travishaagen**
Generate OSGi manifest for `checker-qual`.  Not having this is a big problem for anyone using Guava in an OSGi project.

re: https://github.com/typetools/checker-framework/issues/2065

Shout out to @jlemay who helped figure this out! 

Here's what the `MANIFEST.MF` looks like:

```
Manifest-Version: 1.0
Automatic-Module-Name: org.checkerframework.checker.qual
Bnd-LastModified: 1549483933073
Bundle-ManifestVersion: 2
Bundle-Name: checker-qual
Bundle-SymbolicName: checker-qual
Bundle-Version: 2.5.8
Created-By: 1.8.0_152 (Oracle Corporation)
Export-Package: org.checkerframework.checker.compilermsgs.qual;uses:="
 org.checkerframework.framework.qual";version="2.5.8",org.checkerframe
 work.checker.fenum.qual;uses:="org.checkerframework.framework.qual";v
 ersion="2.5.8",org.checkerframework.checker.formatter;uses:="org.chec
 kerframework.checker.formatter.qual";version="2.5.8",org.checkerframe
 work.checker.formatter.qual;uses:="org.checkerframework.dataflow.qual
 ,org.checkerframework.framework.qual";version="2.5.8",org.checkerfram
 ework.checker.guieffect.qual;uses:="org.checkerframework.framework.qu
 al";version="2.5.8",org.checkerframework.checker.i18n.qual;uses:="org
 .checkerframework.framework.qual";version="2.5.8",org.checkerframewor
 k.checker.i18nformatter;uses:="org.checkerframework.checker.i18nforma
 tter.qual";version="2.5.8",org.checkerframework.checker.i18nformatter
 .qual;uses:="org.checkerframework.framework.qual";version="2.5.8",org
 .checkerframework.checker.index.qual;uses:="org.checkerframework.fram
 ework.qual";version="2.5.8",org.checkerframework.checker.initializati
 on.qual;uses:="org.checkerframework.framework.qual";version="2.5.8",o
 rg.checkerframework.checker.interning.qual;uses:="org.checkerframewor
 k.framework.qual";version="2.5.8",org.checkerframework.checker.lock.q
 ual;uses:="org.checkerframework.framework.qual";version="2.5.8",org.c
 heckerframework.checker.nullness;uses:="org.checkerframework.checker.
 nullness.qual";version="2.5.8",org.checkerframework.checker.nullness.
 qual;uses:="org.checkerframework.framework.qual";version="2.5.8",org.
 checkerframework.checker.optional.qual;uses:="org.checkerframework.fr
 amework.qual";version="2.5.8",org.checkerframework.checker.propkey.qu
 al;uses:="org.checkerframework.framework.qual";version="2.5.8",org.ch
 eckerframework.checker.regex;uses:="org.checkerframework.checker.lock
 .qual,org.checkerframework.checker.nullness.qual,org.checkerframework
 .checker.regex.qual,org.checkerframework.dataflow.qual,org.checkerfra
 mework.framework.qual";version="2.5.8",org.checkerframework.checker.r
 egex.qual;uses:="org.checkerframework.framework.qual";version="2.5.8"
 ,org.checkerframework.checker.signature.qual;uses:="org.checkerframew
 ork.framework.qual";version="2.5.8",org.checkerframework.checker.sign
 edness;uses:="org.checkerframework.checker.signedness.qual";version="
 2.5.8",org.checkerframework.checker.signedness.qual;uses:="org.checke
 rframework.framework.qual";version="2.5.8",org.checkerframework.check
 er.tainting.qual;uses:="org.checkerframework.framework.qual";version=
 "2.5.8",org.checkerframework.checker.units;uses:="org.checkerframewor
 k.checker.units.qual";version="2.5.8",org.checkerframework.checker.un
 its.qual;uses:="org.checkerframework.framework.qual";version="2.5.8",
 org.checkerframework.common.aliasing.qual;uses:="org.checkerframework
 .framework.qual";version="2.5.8",org.checkerframework.common.reflecti
 on.qual;uses:="org.checkerframework.framework.qual";version="2.5.8",o
 rg.checkerframework.common.subtyping.qual;uses:="org.checkerframework
 .framework.qual";version="2.5.8",org.checkerframework.common.util.rep
 ort.qual;uses:="org.checkerframework.framework.qual";version="2.5.8",
 org.checkerframework.common.value.qual;uses:="org.checkerframework.fr
 amework.qual";version="2.5.8",org.checkerframework.dataflow.qual;vers
 ion="2.5.8",org.checkerframework.framework.qual;version="2.5.8",org.c
 heckerframework.framework.util;uses:="org.checkerframework.framework.
 qual";version="2.5.8"
Implementation-URL: https://checkerframework.org
Implementation-Version: 2.5.8
Import-Package: org.checkerframework.checker.formatter.qual,org.checke
 rframework.checker.i18nformatter.qual,org.checkerframework.checker.lo
 ck.qual,org.checkerframework.checker.nullness.qual,org.checkerframewo
 rk.checker.regex.qual,org.checkerframework.checker.signedness.qual,or
 g.checkerframework.checker.units.qual,org.checkerframework.dataflow.q
 ual,org.checkerframework.framework.qual
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.1.0.201810181252
```

### CODE REVIEW

**Comment by mernst** [comment]
You mentioned Guava.  Are similar changes required in Guava itself, or was Guava just an example?
Are you using the annotated version of Guava that is available at
https://mvnrepository.com/artifact/org.checkerframework.annotatedlib/guava
with source at
https://github.com/typetools/guava
?

**Comment by mernst** [comment]
The failing test passed after I pulled upstream.  Thanks for this change!

**Comment by wmdietl** [comment]
Is there a reason to only do this for checker-qual?
Wouldn't this also be useful for the other jars we create?

**Comment by jlemay** [comment]
He was using this guava. https://github.com/google/guava/blob/master/guava/pom.xml

If you look in that pom you will see it uses checker-qual, which adds an import package to the guava manifest file. In OSGi to satisfy the import package there must be a library that exports the package you want to import. Unfortunately,  checker-qual was not an osgi dependency, so the osgi framework would fail with a bundle wiring exception. This is easily solved by generating the manifest osgi headers ourselves, but the proper fix was to fix this in this library. I agree that the other jars created by this project should also generate osgi manifests. It should be pretty straight forward to do this for all your jars by following the pattern in this gradle file.

**Comment by wmdietl** [comment]
@jlemay Thanks for contributing this improvement!
I notice in the build there is now:

```
> Task :checker-qual:jar 
warning: Classpath is empty. Private-Package (-privatepackage) and Export-Package can only expand from the classpath when there is one
```

Is this pointing to some configuration issue?
If not, can we suppress the warning?

**Comment by jlemay** [comment]
I believe that warning is nothing to worry about. This [link](https://github.com/bndtools/bnd/issues/2677#issuecomment-430507934) kinda explains what the issue is and suggests that using `-exportcontents` instead of export package will get rid of the warning. Travis and I are both new to gradle and are just learning about osgi directives in gradle we mostly work with maven.

I think I will give the `exportcontents` a shot and make sure it builds the manifest correctly. Incase you are curious what these instructions are they are based off the bnd tool instruction set. [Here](https://bnd.bndtools.org/chapters/825-instructions-ref.html) is the reference to those instructions.

**Comment by wmdietl** [comment]
Thanks! Please let us know if you find something that should be improved.

**Comment by travishaagen** [comment]
@wmdietl : Replacing `'Export-Package'` with `'-exportcontents'` appears to work correctly. 

If we put up another PR, which other `build.gradle` files would you want us to try adding these directives to? You would only want these on JARs that would be used directly by application code.

**Comment by mernst** [comment]
Thanks for your help!  We appreciate it.
The other JAR used by application code is `checker.jar` (in addition to checker-qual.jar`.

**Comment by wmdietl** [comment]
@travishaagen In #2287 I tried generating this for all jars, but @jlemay pointed out why that won't work.

I think all artifacts on Maven Central should have these OSGI directives, as each one should be usable also for OSGI.
So in addition to `checker`, this would be `javacutil`, `dataflow`, and `framework-test`.

I've filed #2291 to add the missing `framework` artifact, which should similarly contain the OSGI header.

**Comment by travishaagen** [comment]
I took a crack at this, but ran into trouble with the two modules that utilize `shadowJar` to produce the `/dist` output. The OSGi metadata works with the `jar` directive, but when the `shadowJar` is built, it seems to do things its own way. I found this issue:

https://github.com/johnrengelman/shadow/issues/78

If this turns into a bit of a stumbling block, a release with the `checker-qual` OSGi metadata will still be a big help :)

**Comment by wmdietl** [comment]
Thanks for looking into this some more!
This PR is merged, so the next release, around March 1st, will include `checker-qual` with OSGi metadata.

**Pull request merged**
