### PR TITLE
Reopening #1468

### PR DESCRIPTION
**Pull request by kelloggm**
I merged #1468 apparently incorrectly, since the tests failed after I reset the JDK. I suspect that I just did it wrong. Assigning this to @smillst who knows how to do it without breaking everything.

### CODE REVIEW

**Comment by mernst** [comment]
@kelloggm , the JDK is downloaded from 
https://checkerframework.org/dev-jdk/jdk8.jar
The README in that directory
https://checkerframework.org/dev-jdk/README
tells how to update the JDK and what to do when a pull request is failing.
Could you please follow the instructions?  If anything is incorrect, unclear, or missing, your feedback about that will be useful.

**Comment by kelloggm** [comment]
@mernst, @smillst 

I attempted to follow the instructions in the README, but eventually got stuck - I don't have the appropriate permissions to write `/cse/www2/types/checker-framework/dev-jdk`. Running `ls -ld` on the directory results in the following output:

`drwxrwsr-x 2 smillst types_www 4096 Sep  6 10:00 dev-jdk`

I did all of this as myself (i.e. `kelloggm@cs.washington.edu`). I copied a built copy of the JDK to here, so we won't have to build it again: [https://drive.google.com/file/d/0BwRDkhk7JcHKZlpXR0xhN1JjbjQ/view?usp=sharing](https://drive.google.com/file/d/0BwRDkhk7JcHKZlpXR0xhN1JjbjQ/view?usp=sharing)

That JDK was built using a version of this PR that had been merged with master as of 09/06/2017 at 9:00PM pacific time.

I apologize for involving you all in this again, but I don't have permissions and cannot make progress without them. If you can either: give me the appropriate permissions (by, for instance, adding me to the same group as `smillst`) or move the JDK I linked above to the right location and rerun these travis tests, I would appreciate it.

**Comment by smillst** [comment]
@kelloggm  Done.  Thanks!

**Comment by mernst** [comment]
@kelloggm , I added you to the `types_www` group so that you can write to that directory in the future.  (And I updated the documentation to indicate that group membership is a requirement.)

**Pull request merged**
