### PR TITLE
Refactor `CFAbstractStore#methodValues` to `CFAbstractStore#methodCallExpressions`

### PR DESCRIPTION
**Pull request by jyoo980**
@mernst change to a better name, as discussed in our meeting today.

### CODE REVIEW

**Review by mernst — APPROVED** [review]
Two things:
 * This merits a mention in the changelog.
 * This will appear in the next release (tentatively 3.43.1 on June 3), so please assign it to Suzanne to merge when the current release is done.

**Comment by jyoo980** [comment]
@smillst assigning you to merge, now that the previous release is complete.

**Review by mernst — APPROVED** [review]

**Review by smillst — DISMISSED** [review]
Please resolve the conflicts and then this can be merged.

**Review by smillst — APPROVED** [review]

**Comment by jyoo980** [comment]
Will fix after I'm done running some tests locally

**Review by mernst — APPROVED** [review]

**Pull request merged**
