### PR TITLE
Annotate Field.get* and Field.set*'s Object param @Nullable

### PR DESCRIPTION
**Pull request by Pr0methean**
It's nullable if the field is static.

### CODE REVIEW

**Comment by wmdietl** [comment]
But for non-static fields you need a non-null receiver. Our goal is to be conservative and catch potential NPE issues.
We previously discussed this for other reflection methods, e.g. `Method.invoke`: https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/lang/reflect/Method.java#L109

```
    // The method being invoked might be one that requires non-null
    // arguments (including the receiver obj), or might be one that permits
    // null.  We don't know which.  Therefore, the Nullness Checker should
    // conservatively issue a warning whenever null is passed, in order to
    // give a guarantee that no nullness-related exception will be thrown
    // by the invoked method.
```

The same comment applies to these methods in `Field`.
So instead of your change:

```
public Object get(@Nullable Object obj)
```

we would want:

```
public @Nullable Object get(Object obj)
```

with a similar comment about why the receiver is non-null.

**Comment by Pr0methean** [comment]
Okay then, can we maybe have a `@Static` annotation that I can put on Field variables to indicate that they refer to a static field and that the parameter is therefore `@Nullable`? What I don't like is having to annotate `@SuppressWarnings` on the entire class (initializer blocks can't take annotations, at least in JDK 8) just because of one call to `Field.get(null)`. (I'm not sure, in the case of a static field, that the Object parameter even has to be an instance of the class the Field belongs to, but any workaround that relied on assuming otherwise would seem even uglier to me.)

**Comment by Pr0methean** [comment]
We could even add a `castStaticField` helper method to a util class, to check at runtime that the field actually was static. (I'd prefer that over a `getStaticField`, because I'd be able to `-assumenosideeffects` it in Proguard.)

**Comment by mernst** [comment]
Your second proposal of a `@Static` annotation on fields sounds reasonable.
Is this how you would like it to work?

```Field f;
@Static Field sf;
@Nullable Object nullable;
@NonNull Object nonnull;

f.get(nullable);  // warning
f.get(nonnull);   // OK
sf.get(nullable); // OK
sf.get(nonnull);  // OK
```

We would welcome a patch that added that functionality.
If you know what the field is, you could also use/extend the Constant Value Checker instead of a new type system that contains `@Static`.

**Comment by wmdietl** [comment]
I like the `@Static` proposal and @mernst 's examples. This should equally work for the static method case.
Instead of adding this to the Constant Value Checker I would suggest the https://checkerframework.org/manual/#methodval-and-classval-checkers ClassVal and MethodVal Reflection Checker as a suitable place to extend. `@MethodVal` currently describes only the name and number of parameters of a method. `@StaticMethodVal` and `@StaticFieldVal` could describe static methods or field.

Could you change this PR to remove your current `@Nullable` annotations and instead add one to the return type of `getField`? Then we can merge this PR and open a new one for `@Static`.

**Comment by Pr0methean** [comment]
I don't see how the return type of getField would make a difference, since getField itself doesn't return null; you must be talking about a more advanced part of the functionality than I'm familiar with.

**Comment by wmdietl** [comment]
Sorry, I meant `get` should be:

```java
public @Nullable Object get(Object obj)
```

to mark that the field value might be null.
The second parameter to `set` however shouldn't be `@Nullable`, to not allow setting a possibly non-null field to null.

**Comment by Pr0methean** [comment]
Done.

**Comment by mernst** [comment]
Nullness annotations belong in the nullness JDK.  You have added a new file in the index JDK.
In the nullness JDK, the return type of get is [already annotated](https://github.com/typetools/checker-framework/blob/master/checker/jdk/nullness/src/java/lang/reflect/Field.java#L23) as `@Nullable`.
So, I believe that resolves this pull request, since that was the only proposed change.
There is still a feature idea that someone could implement in the future, but we won't keep the issue open just for that.
Thanks!

**Pull request closed without merging**
