### PR TITLE
Remove compiler bootclasspath in CheckerDevelMain (Fixes #3310)

### LINKED ISSUE #3310: Missing specification for a path entry to prepend to the compiler bootclasspath in bin-devel/javac
Running the following command:
` $CHECKER_FRAMEWORK/checker/bin-devel/javac -processor index -implicit:class ArrayLengthLBC.java`
returns the following error:
```
Exception in thread "main" java.lang.AssertionError: CheckerDevelMain.compile.bcp must specify a path entry to prepend to the compiler bootclasspath
        at org.checkerframework.framework.util.CheckerDevelMain.main(CheckerDevelMain.java:49)
```
I think this is due to the deletion of the following line from `checker/bin-devel/javac` when the fix for #3273 was put in:
`     "-DCheckerDevelMain.compile.bcp=${jdkPaths} " \`

### PR DESCRIPTION
**Pull request by MrigankArora**
Fixes #3310

### CODE REVIEW

**Comment by wmdietl** [comment]
Thanks for looking into this issue!
Variable `${jdkPaths}` doesn't seem to be declared, so this will pass an empty string.
I think a proper fix should look at adapting `CheckerDevelMain` and not require the flag at all: https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/util/CheckerDevelMain.java#L49

**Comment by MrigankArora** [comment]
@wmdietl I did as you suggested and adapted `CheckerDevelMain` to not require the flag at all. The CI says that there is documentation missing that needs to be added, but everything else seems good to go.

**Comment by kelloggm** [comment]
@wmdietl I think @MrigankArora is asking for our help in documenting `CheckerDevelMain`. I'm also unsure what the right comment here is, so your help would be appreciated.

**Comment by wmdietl** [comment]
@MrigankArora Thanks for the fix! I've added the missing javadoc.

**Pull request merged**
