### PR TITLE
j.u.Optional: test more methods

### PR DESCRIPTION
**Pull request by t-8ch**
Fixes https://github.com/typetools/checker-framework/issues/4005.
Merge with https://github.com/typetools/jdk/pull/96.

I'm not sure why `mos.orElseThrow(exceptionSupplier);` should be rejected.

### CODE REVIEW

**Comment by mernst** [comment]
> I'm not sure why `mos.orElseThrow(exceptionSupplier);` should be rejected.

The reason is the `@Present` annotation on the receiver of `orElseThrow`.
I think you knew that, and you are wondering why the method has that annotation.
That is explained in the manual in [section "Methods that crash when passed certain values"](https://checkerframework.org/manual/#annotate-normal-behavior-always-crash) (see its last paragraph in particular), and in [section "What the Optional Checker guarantees"](https://checkerframework.org/manual/#optional-guarantees).  Please let us know if this is not clear, so that we can clarify the documentation.

**Comment by t-8ch** [comment]
That makes sense.
I never used the checker framework before and have missed the `@Present` annotation on the receiver.
(And didn't read all of the manual..)
Thanks for explaining!

**Review by mernst — APPROVED** [review]

**Comment by mernst** [comment]
It was confusing (and buggy!) that one `orElseThrow` override had the `@Present` annotation, but the other override lacked the `@Present` override.  I adjusted your pull request to also fix that inconsistency, which might have contributed to your confusion.  Thanks for bringing that to our attention.

**Review by smillst — APPROVED** [review]

**Comment by smillst** [comment]
One of the typetools/jdk#96 jobs failed early this morning.  It looks like the fix in 35ed370, should make it pass, so I reran the failed job.

**Pull request merged**
