### PR TITLE
Made it possible to subclass OverrideChecker in subclasses of BaseTyp…

### PR DESCRIPTION
**Pull request by mcoblenz**
…eVisitor.

### CODE REVIEW

**Comment by mcoblenz** [comment]
The failure doesn't obviously have anything to do with my patch: 

* What went wrong:
Error resolving plugin [id: 'com.github.sherter.google-java-format', version: '0.6']
> Could not GET 'https://plugins.gradle.org/api/gradle/2.10/plugin/use/com.github.sherter.google-java-format/0.6'.
   > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Is this an issue with the test framework, or is it somehow my bug?

**Comment by mernst** [comment]
It's probably a transient failure.  I have re-started the job.

**Comment by mcoblenz** [comment]
I've identified a couple of additional changes that I think are needed here. I'll post them once I have my dependent code working properly. For now, it might make sense to hold off integrating this.

**Comment by mcoblenz** [comment]
I believe this is ready for review and merging (if you approve) now. I suggest squashing. Thanks!

**Comment by wmdietl** [comment]
Thanks for the improvement!

**Comment by mcoblenz** [comment]
Thank you! Any prediction as to when you’ll release the next version? I have a Maven project ready to deploy but I need a version number to depend on.

Michael

**Comment by wmdietl** [comment]
We usually release on the first workday on or after the 1st of each month. So the next release should come out June 1st.

**Pull request merged**
