### PR TITLE
Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by mernst** [comment]
Thanks for this change.  Could you please fix the failing CI job?

**Comment by naveensrinivasan** [comment]
> Thanks for this change. Could you please fix the failing CI job?

It is failing with this. This is a chicken and egg problem. Unless you are looking for me to add that change as part of this PR?
```
@@ -77,6 +77,7 @@ Michal Stehlik,
 Mier Ta,
 Mrigank Arora,
 Narges Shadab,
+Naveen,
 Neil Brown,
 Nhat Dinh,
 Nhat Nguyen,
@@ -122,4 +123,5 @@ Vladimir Sitnikov,
 Vlastimil Dort,
 Weitian Xing,
 Werner Dietl,
-Zhiping Cai.
+Zhiping Cai,
+naveensrinivasan.
+ set +x
docs/manual/contributors.tex is not up to date.
If the above suggestion is appropriate, run: make -C docs/manual contributors.tex
If the suggestion contains a username rather than a human name, then do all the following:
  * Update your git configuration by running:  git config --global user.name "YOURFULLNAME"
  * Add your name to your GitHub account profile at https://github.com/settings/profile
  * Make a pull request to add your GitHub ID to
    https://github.com/plume-lib/plume-scripts/blob/master/git-authors.sed
    and remake contributors.tex after that pull request is merged.
```

**Comment by mernst** [comment]
Yes, the change belongs with this pull request.

**Comment by naveensrinivasan** [comment]
> Yes, the change belongs with this pull request.

@mernst  I tried that it fails. What should I do to fix this issue?

Thanks

**Comment by mernst** [comment]
> @mernst I tried that it fails. What should I do to fix this issue?

You did not follow the instructions.  In particular, you did not do this part:

  * Make a pull request to add your GitHub ID to
    https://github.com/plume-lib/plume-scripts/blob/master/git-authors.sed
    and remake contributors.tex after that pull request is merged.

I have done that for you this time.

**Comment by mernst** [comment]
@naveensrinivasan For some reason I cannot push to your branch.  When making your pull request, did you forbid maintainers from making changes?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan For some reason I cannot push to your branch. When making your pull request, did you forbid maintainers from making changes?

It is part of the org and that is why I don't have an option to allow maintainers to push it.

**Comment by naveensrinivasan** [comment]
> > @naveensrinivasan For some reason I cannot push to your branch. When making your pull request, did you forbid maintainers from making changes?
> 
> It is part of the org and that is why I don't have an option to allow maintainers to push it.

Let me know what you want me to do. Thanks

**Comment by mernst** [comment]
Please run
```
make -C docs/manual contributors.tex
```
, check the resulting change (which should be a single line), and push it.

Thanks!

**Pull request closed without merging**
