### PR TITLE
All characters are NonNegative (JLS 4.2)

### PR DESCRIPTION
**Pull request by kelloggm**
By JLS 4.2, characters are unsigned 16 bit integers. This means that the Index Checker can treat them as `@NonNegative` implicitly, removing some false positives. See kelloggm#192 and [JLS 4.2](https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.2)

### CODE REVIEW

**Comment by mernst** [comment]
@kelloggm The test failure is because the annotated JDK has changed since you started work.  You need to pull from master, rebuild the JDK, and re-upload it; then I believe the tests will pass.

**Comment by kelloggm** [comment]
Thanks for checking this. I'll do that.

**Comment by kelloggm** [comment]
Mike was correct about why the tests weren't passing. @panacekcz, could you review this, please? Thanks!

**Comment by kelloggm** [comment]
I've pushed the test case you suggested into this branch, so I expect the tests to fail. I also fixed two of the problems (the ones with `PolyLowerBound` and `LowerBoundBottom`. I think I should also fix the others if we are going to merge this pull request. Do you think it's worthwhile to do so, or would it be more prudent to simply abandon this and just suppress these warnings?

**Comment by panacekcz** [comment]
I think the linked issues should be fixed sooner or later anyway, after that we can come back here.

**Comment by kelloggm** [comment]
This PR is closed for now, as it needs significantly more work to bring to a mergable state that I don't have time to do for now. I will reopen it once that work is completed.

**Pull request closed without merging**
