### PR TITLE
A change that should break the build, to test whether travis correctly

### PR DESCRIPTION
**Pull request by wmdietl**
builds pull requests.

### CODE REVIEW

**Comment by wmdietl** [comment]
Related to my questions to this commit: https://github.com/typetools/checker-framework/commit/349829651017cb383c2c1b29ce541ad6c756847b

**Comment by smillst** [comment]
@wmdietl I added a commit (deeb705) to this branch that should fix the problem.  (So if my fix is correct, Travis should fail on this branch.)

**Comment by wmdietl** [comment]
Thanks, that looks good!

**Comment by smillst** [comment]
Thanks for spotting this!  I pushed the commit that fixes this to master (e67713c).

**Pull request closed without merging**
