### PR TITLE
Remove annotations in comments from checker package

### PR DESCRIPTION
**Pull request by smillst**
We could remove annotations in comments from the framework package, too, but that would make it depend on annotations in the checker package.  (Note that the annotations in Util class that go into checker-qual.jar will still have annotations in comments since they are still built with -source 7 -target 7.)

### CODE REVIEW

**Comment by mernst** [comment]
Here are some annotations in comments that look like they could be uncommented. Could you check them out?

```
tests/index/Index115.java:17:37:    public static void main3(String /*@ArrayLen({1,2})*/[] args) {
tests/index/Index115.java:23:37:    public static void main4(String /*@ArrayLen({1,2})*/... args) {
tests/nullness/Issue415.java:4:1:/*>>>
tests/nullness/Issue415.java:18:38:    public static void usesField(Set</*@KeyFor("this.mymap")*/ String> keySet) {
tests/nullness/Issue415.java:20:23:        new ArrayList</*@KeyFor("this.mymap")*/ String>(keySet);
tests/nullness/Issue415.java:23:66:    public static void usesParameter(Map<String, Integer> m, Set</*@KeyFor("#1")*/ String> keySet) {
tests/nullness/Issue415.java:24:23:        new ArrayList</*@KeyFor("#1")*/ String>(keySet);
tests/nullness/Issue415.java:27:66:    public static void sortedKeySet1(Map<String, Integer> m, Set</*@KeyFor("#1")*/ String> keySet) {
tests/nullness/Issue415.java:28:23:        new ArrayList</*@KeyFor("#1")*/ String>(keySet);
tests/nullness/Issue415.java:32:13:        Set</*@KeyFor("#1")*/ String> keySet = m.keySet();
tests/nullness/Issue415.java:36:13:        Set</*@KeyFor("#1")*/ String> keySet = m.keySet();
tests/nullness/Issue415.java:37:23:        new ArrayList</*@KeyFor("#1")*/ String>(keySet);
tests/nullness/Issue415.java:41:23:        new ArrayList</*@KeyFor("#1")*/ String>(m.keySet());
tests/nullness/Issue415.java:45:23:        new ArrayList</*@KeyFor("#1")*/ K>(m.keySet());
tests/nullness/Issue653.java:8:19:    public static /*@PolyAll*/ String[] concat(
tests/nullness/Issue653.java:9:13:            /*@PolyAll*/ String /*@Nullable*/ [] a, /*@PolyAll*/ String /*@Nullable*/ [] b) {
tests/nullness/Issue653.java:20:17:                /*@PolyAll*/ String[] result = new String[a.length + b.length];
tests/nullness/InitSuppressWarnings.java:9:13:            /*>>> @UnderInitialization(Object.class) @Raw InitSuppressWarnings this*/) {
tests/nullness/InitSuppressWarnings.java:11:9:        /*@Initialized*/ /*@NonRaw*/ InitSuppressWarnings initializedThis = this;
tests/nullness/Issue414.java:17:21:    void semiSimple(/*@KeyFor("this.someField")*/ String s) {
tests/nullness/Issue414.java:20:9:        /*@KeyFor({"this.someField","mymap"})*/ String s2 = s;
tests/nullness/Issue414.java:26:9:        /*@KeyFor({"preds","dom"})*/ String root;
tests/nullness/Issue414.java:28:14:        List</*@KeyFor({"preds","dom"})*/ String> roots = new ArrayList<String>();
tests/nullness/Issue414.java:41:9:        /*@KeyFor({"preds","dom"})*/ T root;
tests/nullness/Issue414.java:43:14:        List</*@KeyFor({"preds","dom"})*/ T> roots = new ArrayList<T>();
tests/nullness/java8/Issue596.java:18:48:    public static <T> Optional<T> fromNullable(/*@Nullable*/ T nullableReference) {
tests/nullness/BinaryOp.java:5:15:    void test(/*@UnknownInitialization*/ /*@Raw*/ Object obj) {
tests/nullness/Stats.java:8:5:    /*@Nullable*/ Map<Integer, String> inv_map = null;
tests/nullness/InitializedField.java:16:5:    /*@RequiresNonNull("stack")*/
tests/nullness/InitializedField.java:17:25:    public Object iPeek(/*>>>@UnknownInitialization @Raw InitializedField this*/) {
tests/nullness/KeyForStaticField.java:21:29:    public Integer getValue(/*@KeyFor("this.map")*/ String key) {
tests/all-systems/FieldWithInit.java:5:16:    Object foo(/*@UnknownInitialization @Raw*/ FieldWithInit this) {
jdk/index/src/java/lang/Character.java:4807:49:    public static int codePointBefore(char[] a, /*@Positive @LTEqLengthOf("#1")*/ int index) {
jdk/index/src/java/lang/Character.java:4838:49:    public static int codePointBefore(char[] a, /*@Positive @LTEqLengthOf("#1")*/ int index, @IndexOrHigh("#1") int start) {
src/org/checkerframework/checker/units/UnitsRelations.java:7:1:/*>>>
src/org/checkerframework/checker/units/UnitsRelations.java:29:5:    /*@Nullable*/ AnnotationMirror multiplication(AnnotatedTypeMirror lht, AnnotatedTypeMirror rht);
src/org/checkerframework/checker/units/UnitsRelations.java:39:5:    /*@Nullable*/ AnnotationMirror division(AnnotatedTypeMirror lht, AnnotatedTypeMirror rht);
```

**Comment by smillst** [comment]
I've removed all the annotations in comments in the files you listed.

**Comment by mernst** [comment]
This looks good, thanks.
Some examples still use the annotations-in-comments syntax; see below.  Are they intentionally held back at Java 7 syntax, or can they be upgraded?
```
docs/examples/NullnessExample.java:29:14:        List</*@NonNull*/ String> foo = new LinkedList</*@NonNull*/ String>();
docs/examples/NullnessExample.java:30:14:        List</*@NonNull*/ String> bar = foo;
docs/examples/NullnessExampleWithWarnings.java:27:12:    public /*@NonNull*/ String exampleGenerics() {
docs/examples/NullnessExampleWithWarnings.java:29:14:        List</*@NonNull*/ String> foo = new LinkedList</*@NonNull*/ String>();
docs/examples/NullnessReleaseTests.java:20:14:        List</*@NonNull*/ String> foo = new LinkedList</*@NonNull*/ String>();
docs/examples/NullnessReleaseTests.java:21:14:        List</*@NonNull*/ String> bar = foo;
docs/examples/GradleExamples/GradleJava7Example/src/main/java/org/checkerframework/example/GradleExample.java:2:1:/*>>>
docs/examples/GradleExamples/GradleJava7Example/src/main/java/org/checkerframework/example/GradleExample.java:26:19:    public static /*@Nullable*/ Object nullable = null;
docs/examples/GradleExamples/GradleJava7Example/src/main/java/org/checkerframework/example/GradleExample.java:33:9:        /*@NonNull*/ Object nn = nullable; // error on this line
docs/examples/GradleExamples/GradleJava7Example/src/main/java/org/checkerframework/example/GradleExample.java:35:14:        List</*@NonNull*/ String> list = new ArrayList<>();
eclipse/checker-framework-eclipse-plugin/src/org/checkerframework/eclipse/actions/CheckerHandler.java:27:15:    protected /*@Nullable*/ List<IJavaElement> selectionToJavaElements(final ISelection selection) {
```

**Comment by smillst** [comment]
I corrected the ones you listed except for `docs/examples/GradleExamples/GradleJava7Example/src/main/java/org/checkerframework/example/GradleExample.java`.  That one is an example of how to configure Gradle to use annotations in comments.

**Pull request merged**
