### PR TITLE
Non-Empty Checker

### PR DESCRIPTION
**Pull request by mernst**
Merge together with:
 * https://github.com/typetools/jdk/pull/208
 * https://github.com/typetools/jdk17u/pull/8
 * https://github.com/plume-lib/plume-util/pull/403

### CODE REVIEW

**Comment by jyoo980** [comment]
@smillst I'd appreciate a review from you for this code.

**Review by smillst — APPROVED** [review]
I just had on minor comment. Plus I made a correction bf88adec and added a test case b794b630.

**Comment by jyoo980** [comment]
@smillst I have addressed your review comments, and in doing so, dismissed your approval. Sorry!

**Review by smillst — DISMISSED** [review]

**Comment by mernst** [comment]
@jyoo980 Please re-open under your account.

**Pull request closed without merging**
