### PR TITLE
Note about renaming

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

**Comment by mernst** [comment]
@kelloggm Do you understand the reason for a test failure with a class renaming?

**Comment by kelloggm** [comment]
> Do you understand the reason for a test failure with a class renaming?

@mernst No, I do not. The error in the log is caused by using an ajava file that was generated from the test input before it was renamed. However, there is no such `.ajava` file checked-in (which was my first suspicion).

Is it possible that the CI machines have corrupted gradle caches? That's the only plausible thing that I can think of that might cause a failure like this one.

Have you tried to rerun CI or to reproduce the problem locally? It's possible that it's transient, if it's related to the gradle cache.

**Comment by mernst** [comment]
@kelloggm I have re-run CI many times, and I have also reproduced the problem locally.  I'm befuddled.

**Comment by kelloggm** [comment]
@mernst I made the change in the location that your comment indicated again myself and the tests passed locally. I'm running CI now to see whether they also pass in CI.

I notice that the commit history includes some other renamings besides the specific one that you pointed me to in this PR. Would you like me to look into any of those, too?

**Comment by mernst** [comment]
@kelloggm Thanks!  I tried quite a number of things.  If this one you did works, I'm happy.

**Pull request merged**
