### PR TITLE
Add NetBeans Checker Framework plugin

### PR DESCRIPTION
**Pull request by Haaris710**

### CODE REVIEW

**Comment by wmdietl** [comment]
This PR continues the work from #990 and documents the current restrictions with different Netbeans versions.

**Comment by Haaris710** [comment]
An inability to set the bootclass path and lack of compatibility of the exisiting plugin with jdk 9 has resulted in an inability to add a working Netbeans 8.2 Checker Framework Plugin. This pull request should be closed until a solution can be found. @wmdietl

**Comment by wmdietl** [comment]
Right, this PR should be closed.
Can you make a new PR that adds a note to the manual, e.g. cherry-pick https://github.com/typetools/checker-framework/pull/1592/commits/788b60414182296ad8ba2c0db62088a72c78873b.
Maybe a latex-comment can reference this PR to make it easier to find this work again.

**Comment by wmdietl** [comment]
Replaced by #1834

**Pull request closed without merging**
