### PR TITLE
add @RequiresCalledMethods annotation

### PR DESCRIPTION
**Pull request by kelloggm**

### CODE REVIEW

**Review by mernst — CHANGES_REQUESTED** [review]
Could you please add a reference to the new annotation in the manual?

**Comment by kelloggm** [comment]
@mernst thanks for reminding me to do so! That's now done, so this should be ready for review.

**Review by mernst — CHANGES_REQUESTED** [review]
Could you please add the missing Javadoc?  (See CI failures.)

**Comment by kelloggm** [comment]
@mernst I've added the javadoc. Thanks for fixing the CI script!

**Review by mernst — APPROVED** [review]

**Pull request merged**
