### PR TITLE
Updating IntelliJ instructions

### PR DESCRIPTION
**Pull request by NhatDinh**
As discussed in [Issue #1906 ](https://github.com/typetools/checker-framework/issues/1906).
I have updated IntelliJ instructions from 15.0.3 to 2017.3.4 CE
Refactor "create annotation profile and specify which checkers to run"
Fix a minor typo in gsoc-ideas.html
Files changed:
docs/manual/external-tools.tex
docs/developer/gsoc-ideas.html

### CODE REVIEW

**Comment by NhatDinh** [comment]
Hi, I have resolved merge conflicts.

**Comment by NhatDinh** [comment]
How can I solve "All checks have failed" in this case?
Thank you,
-Nhat

**Comment by NhatDinh** [comment]
Hi,
Please let me know why "All checks have failed" and how to resolve it. 
Thank you.

**Comment by smillst** [comment]
If you click [Details](https://travis-ci.org/typetools/checker-framework/builds/360116185?utm_source=github_status&utm_medium=notification), then you can see what tests failed.  In the case, the problem is that the manual won't build:
https://travis-ci.org/typetools/checker-framework/jobs/360116189#L5105

**Pull request closed without merging**
