### PR TITLE
Remove broken compilerPom installation.

### PR DESCRIPTION
**Pull request by wmdietl**
There is no `maven-artifacts/poms/compilerPom.xml` file.

### CODE REVIEW

**Comment by wmdietl** [comment]
Should each sub-project create a separate `dist`, e.g. should there be a `framework/dist/framework.jar`?
Or does that only make sense for `checker/dist`, which contains the fat jar and dependencies, mostly for the release.
Or is this file just out-of-date and should be completely removed?

**Comment by wmdietl** [comment]
Also note that shadowjar, in particular `./gradlew framework:shadowjar` creates a fat `framework/dist/framework.jar` file.

**Comment by smillst** [comment]
>Should each sub-project create a separate dist, e.g. should there be a framework/dist/framework.jar?
Or does that only make sense for checker/dist, which contains the fat jar and dependencies, mostly for the release.

Only checker has a `dist` because that's where the checker fat jar is and dependencies needed for checker/bin/javac.  The other projects follow the Gradle convention of putting jars in .

>Or is this file just out-of-date and should be completely removed?

Yes.  (I mean if you find it useful we could update it, but it's not currently used.)

**Comment by smillst** [comment]
>Also note that shadowjar, in particular ./gradlew framework:shadowjar creates a fat framework/dist/framework.jar file.

I'd forgotten that.  The other shadowjars are in `build/libs/dataflow-2.8.0-all.jar`

**Comment by wmdietl** [comment]
A somewhat related question: do we need the pom files in `https://github.com/typetools/checker-framework/tree/master/maven-artifacts/poms` at all?
Don't the files in `maven-artifacts/release` simply contain more information?
Could we remove the files in `poms` and only keep the versions in `release`, moved to a proper location one level up?

**Comment by smillst** [comment]
The poms in maven-artifacts/poms are used in the release to test the maven artifacts. I don’t know if the release poms could be used for these tests or not.

**Comment by smillst** [comment]
>Do we need the pom files in https://github.com/typetools/checker-framework/tree/master/maven-artifacts/poms at all?

Yes, because these poms are for releasing to https://checkerframework.org/dev/m2-repo, which we do during the release.

**Comment by mernst** [comment]
> > Do we need the pom files in https://github.com/typetools/checker-framework/tree/master/maven-artifacts/poms at all?
> 
> Yes, because these poms are for releasing to https://checkerframework.org/dev/m2-repo, which we do during the release.

It might be good to document that purpose in a README in that directory.

**Comment by wmdietl** [comment]
I'll test whether we can use the same poms for both purposes. The duplication is hard to maintain. Maybe a simple script could filter out parts that are not allowed for the local installation.

**Pull request merged**
