### PR TITLE
Non-Empty Checker + Optional Checker

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

**Comment by jyoo980** [comment]
Supersedes  https://github.com/typetools/checker-framework/pull/6607

**Comment by jyoo980** [comment]
@mernst The test failures you're seeing in the Non-Empty Checker specific tests come from the fact that it has the Optional Checker as a subchecker, which will only pass it methods to verify which contain explicitly-written annos from the Non-Empty type system.

When I remove this relationship, all tests related to the Non-Empty type system pass.

We could create a flag that disables the Optional Checker if passed in, enabling users (and the test) to run it as a standalone checker.

**Review by mernst — COMMENTED** [review]
The Non-Empty Checker has an odd contract: *by default* it runs the Optional Checker and only checks part of the program.  I suggest:
 * the fact that there are two modalities in which the Non-Empty Checker can be run should be documented.
 * the default should be to run the Non-Empty Checker like any other checker
 * the argument to switch between the modalities should be renamed

**Comment by mernst** [comment]
Closing so James can re-open.

**Pull request closed without merging**
