### PR TITLE
Convert all type annotations to CheckerFrameworkAnnotationMirrors

### PR DESCRIPTION
**Pull request by smillst**

### CODE REVIEW

**Comment by wmdietl** [comment]
@nhat-nguyen could you please have a look whether this has a positive impact on execution time (it uses interned strings) vs. memory consumption (it creates wrapper objects)?

**Comment by nhat-nguyen** [comment]
> @nhat-nguyen could you please have a look whether this has a positive impact on execution time (it uses interned strings) vs. memory consumption (it creates wrapper objects)?

I'll make sure to profile this. This PR is very similar to my proposed idea of wrapping every annotation and perform a one-time pass over all annotations and assign each of them a hash value so that we don't have to repeatedly compare their string representation in AnnotationUtils.

@smillst I have one quick question, if now all type annotations are wrapped inside `CheckerFrameworkAnnotationMirror`, isn't the `instanceof` check in `areSameByName(AnnotationMirror a1, AnnotationMirror a2)` unnecessary? Or can there still be javac's annotation as well?

**Comment by wmdietl** [comment]
> I'll make sure to profile this. This PR is very similar to my proposed idea of wrapping every annotation and perform a one-time pass over all annotations and assign each of them a hash value so that we don't have to repeatedly compare their string representation in AnnotationUtils.

Is there something in  `CheckerFrameworkAnnotationMirror` that could be improved to do that?

> @smillst I have one quick question, if now all type annotations are wrapped inside `CheckerFrameworkAnnotationMirror`, isn't the `instanceof` check in `areSameByName(AnnotationMirror a1, AnnotationMirror a2)` unnecessary? Or can there still be javac's annotation as well?

At the moment the parameters allow arbitrary `AnnotationMirror`s, so the instanceof is necessary. That probably isn't costing a lot.

**Comment by smillst** [comment]
>@smillst I have one quick question, if now all type annotations are wrapped inside CheckerFrameworkAnnotationMirror, isn't the instanceof check in areSameByName(AnnotationMirror a1, AnnotationMirror a2) unnecessary? Or can there still be javac's annotation as well?

All _type_ annotations are converted to CheckerFrameworkAnnotationMirrors, but _declaration_ annotations are not.  So the util methods in AnnotationUtils still need to expect both.

**Comment by smonteiro** [comment]
When will this be merged into master ? 
It looks better than it was.
Once this is merged I have an improvement to offer on this issue of *areSame*().

**Comment by mernst** [comment]
@nhat-nguyen
> I'll make sure to profile this.

What was the result of your profiling?

Azure Pipelines shows a slowdown.
Either this branch degrades performance, or Azure Pipelines is not useful for profiling.
It would be useful to know which is the case.
Here is timing information from Azure Pipelines:
In this branch, the daikon_jdk8 job takes 47:33 :
https://dev.azure.com/typetools/checker-framework/_build/results?buildId=2046&view=logs&jobId=458a3e2d-91a0-5e1b-309f-8f24fd6215b9
In master, the daikon_jdk8 job takes 41:12 :
https://dev.azure.com/typetools/checker-framework/_build/results?buildId=2131&view=logs&jobId=458a3e2d-91a0-5e1b-309f-8f24fd6215b9

**Comment by nhat-nguyen** [comment]
@wmdietl @mernst I'm sorry for the delay in getting the results. I just ran this branch 15 times using `time -v` with https://github.com/typetools/checker-framework/issues/1889 (1600 fields) as a micro-benchmark and nullnessfbctest (type-checking daikon took too long on my machine to run) and had the following results (attached).

[baseline.txt](https://github.com/typetools/checker-framework/files/3909174/baseline.txt)
[wrapper.txt](https://github.com/typetools/checker-framework/files/3909175/wrapper.txt)

The timings on my laptop look a bit odd since the wrapper is actually somehow a bit faster. But the memory usage seems pretty much the same.

**Comment by wmdietl** [comment]
@nhat-nguyen Thanks for profiling!

Performance numbers seem to not show performance improvements and I dislike making `CheckerFrameworkAnnotationMirror` public.

@smonteiro You mentioned possible improvements that build on this change.
Was that for the changes that we already merged or for these remaining changes?
Can you give some more details what this would enable?
Thanks!

**Comment by smonteiro** [comment]
@wmdietl  Definitely I can try to explain briefly. on a  separate issue so I do not cloud this one. It would be applicable either way but I did not want to interfere with this effort.. Let me do that.

**Comment by smonteiro** [comment]
See #2958 for another approach to this.

**Comment by smillst** [comment]
Since this doesn't improve performance, I'm closing it.  @nhat-nguyen, thanks for testing this!

**Pull request closed without merging**
