### PR TITLE
Add java.util.Map to index jdk

### PR DESCRIPTION
**Pull request by panacekcz**
Adds `java.util.Map` to the index jdk.
The only annotation is `@NonNegative int size();`.

Fixes kelloggm#184.

### CODE REVIEW

**Comment by smillst** [comment]
Also, please don't merge to master until after I have made the release.  (Which should happen later today.)

**Comment by mernst** [comment]
When merging this pull request, remember to update the downloaded JDK.

**Comment by kelloggm** [comment]
This PR is being tested using an annotated JDK off to the side (since there wasn't one in the PR originally).

Once that's done, I'll move that JDK into the standard download location, and rerun the tests.

**Comment by kelloggm** [comment]
@panacekcz, the tests are failing on this PR when I tested it using a JDK built from your branch. Do you know why?

**Comment by panacekcz** [comment]
Yes, you merged #1626 to master, so the tests from that PR are run, but the annotations from that PR are not in the used jdk.

**Comment by kelloggm** [comment]
JDK is updated; merge when tests pass.

**Pull request merged**
