### PR TITLE
Fix Issue #457

### PR DESCRIPTION
**Pull request by JonathanBurke**
Make the instanceof operand the backup type when calculating mostSpecific
This a fix for https://github.com/typetools/checker-framework/issues/457

### CODE REVIEW

**Comment by mernst** [comment]
Should the pull request also uncomment or add a test in the test suite?

**Comment by JonathanBurke** [comment]
That's a good point.  Werner mentioned in the issue that he added a test case but I don't think he pushed it.  I've been meaning to ask him because I don't see a commit and find/grep turns up nothing.

I'll send him a message.  If he hasn't added a test case, I will add my simpler example and add a link to the issue/this request in the comments.

**Comment by wmdietl** [comment]
Sorry for not pushing the test case. It was exactly the test as submitted.
Please add your simpler example instead.
The fix itself makes sense. Please merge when you added the test.

**Comment by JonathanBurke** [comment]
I have pushed the test.  I will wait till the travis test finishes and then merge.

**Pull request merged**
