### PR TITLE
Clone JSpecify, now that its build works again across JDKs.

### PR DESCRIPTION
**Pull request by netdpb**
This reverts commit 803bc76c71944cf53956771b669c570dc2ea3517.

### CODE REVIEW

**Comment by mernst** [comment]
Hi, David.  CI doesn't run the JSpecify tests, so this change would only add time to the CI build. (It would also test that JSpecify didn't break its build again, but I think that is better done in the JSpecify repository.)  Is there some other reason to make this change?  Thanks!

**Comment by netdpb** [comment]
I agree, and I'm only doing this because we've made that change. (The problem was that JSpecify's CI only tested JDK 11, and even then didn't generate Javadoc.)

If CF's CI doesn't need to run the JSpecify tests, can we delete this entire stanza rather than commenting it out and implying that that's a problem?

**Comment by mernst** [comment]
That's a good idea.  The comment wasn't meant to throw any shade on JSpecify, and was accurate at the time.

**Comment by netdpb** [comment]
Does the build still rely on this script cloning the JSpecify repo? Can I delete everything, or should I keep the git clone?

The fact that the build jumps around between Gradle and shell-scripting makes it hard to understand what's required.

**Comment by mernst** [comment]
@netdpb I cannot find the `jspecify-ci` branch in your fork any more.

**Comment by netdpb** [comment]
Looks like it got cleaned up for being stale.

**Pull request closed without merging**
