### PR TITLE
Make RLC's ignored exception types consistent

### PR DESCRIPTION
**Pull request by kelloggm**

### CODE REVIEW

**Review by msridhar — COMMENTED** [review]
LGTM, but do we want to take the opportunity to update the manual for the RLC in terms of what kinds of exceptional behaviors are ignored?

**Comment by kelloggm** [comment]
That's a good idea. The current manual section doesn't mention it at all, but I've added a new section at the end of the manual chapter that's dedicated entirely to exceptions. It is not comprehensive, but I think it touches on the most important points.

**Review by msridhar — APPROVED** [review]
LGTM

**Comment by kelloggm** [comment]
@mernst, can you take a look at this PR, especially at the new manual text? If you think it looks good, you can go ahead and merge it.

**Review by mernst — APPROVED** [review]

**Pull request merged**
