### PR TITLE
Initialize implicit this.

### PR DESCRIPTION
**Pull request by smillst**

### CODE REVIEW

**Review by mernst — DISMISSED** [review]
Thanks!

**Comment by mernst** [comment]
@smillst Tests are failing.

**Comment by jyoo980** [comment]
The following test case is failing:

```java
@EnsuresNonEmptyIf(result = false, expression = "this")
public boolean isEmpty2() {
  return size() == 0 ? true : false;
}
```

And I'm wondering now if it's still a valid test case. Is there enough information to determine whether the container is indeed non-empty in the case that this method returns `false`?

For context, the implementation of `size()` used in this method is:

```java
@Pure
@Override
public int size() {
  return -1;
}
```

Which overrides the `size()` method provided by the JDK.

**Comment by smillst** [comment]
> And I'm wondering now if it's still a valid test case. Is there enough information to determine whether the container is indeed non-empty in the case that this method returns `false`?

I think it is.  The non-empty checker is assuming that size is implemented correctly.  Also the other two similar test cases in that file still pass.

```
  @EnsuresNonEmptyIf(result = false, expression = "this")
  public boolean isEmpty3() {
    return size() == 0;
  }
```
```
  @Pure
  @Override
  @EnsuresNonEmptyIf(result = false, expression = "this")
  public boolean isEmpty() {
    if (size() == 0) {
      return true;
    } else {
      return false;
    }
  }
```

So I think this failure indicates a bug somewhere in dataflow.  Conditional expressions have a different implementation than if statements in dataflow.  I'm working on this now.

**Comment by jyoo980** [comment]
@smillst I see, thanks!

**Review by mernst — APPROVED** [review]

**Pull request merged**
