### PR TITLE
Script to compute list of currently-supported type qualifiers

### PR DESCRIPTION
**Pull request by kelloggm**
Based on https://github.com/plume-lib/run-google-java-format/blob/88a9e5281abdffba21b8637e8a4ade4e748bd10e/fixup-google-java-format.py#L33

### CODE REVIEW

**Comment by kelloggm** [comment]
@dd482IT here is the script I used to compute the list of qualifiers I sent to @LoiNguyenCS a few minutes ago (which he was blocked on getting). I know you were looking at this script at some point, so I thought you might find this PR interesting.

**Comment by dd482IT** [comment]
@kelloggm Thank you, It may come in handy.

**Comment by mernst** [comment]
@kelloggm Could you take a look at the changes I made?

**Comment by kelloggm** [comment]
@mernst these changes look good. I've enabled auto-merge (and the tests have passed), so this should merge as soon as you approve it.

**Review by mernst — APPROVED** [review]

**Pull request merged**
