### PR TITLE
Annotated all `Object clone()` as PolySameLen

### PR DESCRIPTION
**Pull request by Kakarot-SSJ4**

### CODE REVIEW

**Comment by Kakarot-SSJ4** [comment]
@kelloggm Fixed the unnecessary diff.

**Comment by Kakarot-SSJ4** [comment]
@kelloggm @panacekcz

**Comment by kelloggm** [comment]
Remind me why we need this PR?

I'm generally hesitant to add annotations to common methods like `clone()`, which should probably be `@PolyAll` anyway in the annotated JDK already.

**Comment by Kakarot-SSJ4** [comment]
@kelloggm Because the checker does not infer an array1 = array2.clone() to have same length as array2

**Comment by kelloggm** [comment]
Closing because we don't think the benefits of this change outweigh the additional annotation burden.

**Pull request closed without merging**
